# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95138017f8e8e307dbd6c8ecf83accb989ef65d855e28eef5895a57f547020bfc550e72f36b67da44f29cf2b50cd752f78e5bb5e4ba2f02da52ba5fc2980bb52

test:
  secret_key_base: d0fed220e3876816073204eddeb62e60175fb3a109ca3d6c4d796602a4971dcc0770f0b1c90f13922a1b5e4e01c00ba7eb50b0660d8409d9862d7e519725d629

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
